"""empty message

Revision ID: 191c78407151
Revises: 4357f5dcc564
Create Date: 2015-12-11 21:56:00.136433

"""

# revision identifiers, used by Alembic.
revision = '191c78407151'
down_revision = '4357f5dcc564'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('minecraft_product', sa.Column('description', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['username'])
    op.add_column('ventrilo_product', sa.Column('description', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventrilo_product', 'description')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('minecraft_product', 'description')
    ### end Alembic commands ###
