"""empty message

Revision ID: 31140971ff88
Revises: 191c78407151
Create Date: 2015-12-11 22:07:02.313361

"""

# revision identifiers, used by Alembic.
revision = '31140971ff88'
down_revision = '191c78407151'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mcproduct', sa.Integer(), nullable=True),
    sa.Column('ventproduct', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mcproduct'], ['minecraft_product.id'], ),
    sa.ForeignKeyConstraint(['ventproduct'], ['ventrilo_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(u'subscription_productid_fkey', 'subscription', type_='foreignkey')
    op.create_foreign_key(None, 'subscription', 'order_product', ['productid'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.create_foreign_key(u'subscription_productid_fkey', 'subscription', 'minecraft_product', ['productid'], ['id'])
    op.drop_table('order_product')
    ### end Alembic commands ###
