"""empty message

Revision ID: 4357f5dcc564
Revises: None
Create Date: 2015-12-11 21:49:25.786585

"""

# revision identifiers, used by Alembic.
revision = '4357f5dcc564'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minecraft_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dedicated_ram', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ventrilo_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slots', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('startdate', sa.DateTime(), nullable=True),
    sa.Column('enddate', sa.DateTime(), nullable=True),
    sa.Column('productid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['productid'], ['minecraft_product.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription')
    op.drop_table('ventrilo_product')
    op.drop_table('user')
    op.drop_table('minecraft_product')
    ### end Alembic commands ###
